version: '2'

networks:
  my_network:
    driver: bridge
services:
  app:
    image: fastapi:latest
    ports:
      - "8000:8000"
    name: app
    volumes:
      - ./app:/app:rw
    networks:
      - my_network
    depends_on:
      - mariadb
    command: uvicorn app.main:app --reload

  nifi:
    image: apache/nifi:latest
    name: nifi
    networks:
      - my_network
    ports:
      - "8080:8080"
    volumes:
      - ./nifi:/opt/nifi/nifi-current/conf:ro
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME=admin
      SINGLE_USER_CREDENTIALS_PASSWORD=admin
    depends_on:
      - minio
      - fastapi
      - ollama
    command: 
      - apt-get update && apt-get install -y python3-pip && pip3 install requests
      - pip install pandas, numpy
  
  mariadb:
    image: mariadb:latest
    name: mariadb
    environment:
      MARIADB_ROOT_DATABASE: fashionworld
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_USER: admin
    volumes:
      - ./mariadb
    networks:
      - my_network
  
  ollama:
    image: ollama/ollama:latest
    name: ollama
    networks:
      - my_network
    volumes:
      - ./ollama:/root/.ollama:rw
    command: "ollama pull llama3.2:4b"

  minio:
    image: minio/minio:latest
    name: minio
    networks:
      - my_network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    volumes:
      - ./minio:/data:rw
    command: server /data